### ISSUE TITLE
lightline.vim 问题

### ISSUE THREAD

**Issue by flyingalex** [fgheng/vime#1]
感谢开源你的配置，组织太好了, 🐂🍺!!!

发现一个问题，
lightline状态栏在mac上全是问号，

![image](https://user-images.githubusercontent.com/11313145/88606064-4a709300-d0ae-11ea-87f3-1e7ba12f5f78.png)

然后看到lightline配置好像未识别
![image](https://user-images.githubusercontent.com/11313145/88606103-62e0ad80-d0ae-11ea-8c9c-da0b6124eca8.png)

有机会更新一下吗? 谢谢

另外还有个问题，感觉所有主题都只有在tmux内才能正常显示，有办法让它在普通终端正常显示
没找到配置在哪？

**Comment by fgheng** [comment]
你好，第二张截图上的符号都是口字，应该是mac的终端不支持这些符号的显示，我用的linux，终端上显示正常。
![image](https://user-images.githubusercontent.com/50551377/88870907-29907500-d249-11ea-8732-29cacd0ba791.png)
不过解决方法也很简单，你可以从网络上查找一些符号然后复制到终端里看看是否显示正常，如果正常显示的话可以用新的符号替换第二张截图里的符号。
因为我没有mac，所以我也不太清楚哪些符号可以正常在mac上显示，我不太清楚有没有什么方法可以避免这种情况的发生，如果你知道的话可以告诉我。


我关于主题的配置都是在`config/theme.vim`文件中的，我只是用了一个colorschem选择了一个主题，没有其他的配置了，应该与tmux没有关系啊。

**Comment by flyingalex** [comment]
谢谢，我试试
