### ISSUE TITLE
nvim-treesitter-textobjects.vim 时发生 错误

### ISSUE THREAD

**Issue by chianman719** [fgheng/vime#16]
处理 /home/yu/.config/nvim/config/plugins/nvim-treesitter-textobjects.vim 时发生
错误:
第   86 行:
E5105: Error while calling lua chunk: ...im/plugins/nvim-treesitter/lua/nvim-tre
esitter/query.lua:2: module 'vim.treesitter.query' not found:
        no field package.preload['vim.treesitter.query']
        no file '/home/yu/.config/nvim/lua/vim/treesitter/query.lua'
        no file '/home/yu/.config/nvim/lua/vim/treesitter/query/init.lua'
        no file '/home/yu/.cache/vim/plugins/coc.nvim/lua/vim/treesitter/query.l
ua'
        no file '/home/yu/.cache/vim/plugins/coc.nvim/lua/vim/treesitter/query/i
nit.lua'
        no file '/home/yu/.cache/vim/plugins/fzf/lua/vim/treesitter/query.lua'
        no file '/home/yu/.cache/vim/plugins/fzf/lua/vim/treesitter/query/init.l
ua'
        no file '/home/yu/.cache/vim/plugins/fzf-gitignore/lua/vim/treesitter/qu
ery.lua'
        no file '/home/yu/.cache/vim/plugins/fzf-gitignore/lua/vim/treesitter/qu
ery/init.lua'
        no file '/home/yu/.cache/vim/plugins/fzf.vim/lua/vim/treesitter/query.lu
a'
        no file '/home/yu/.cache/vim/plugins/fzf.vim/lua/vim/treesitter/query/in
it.lua'

这是什么包没安装吗？

**Comment by fgheng** [comment]
您好，请问您使用的是最新的neovim么？
我之前没有使用最新的neovim的时候也会出现问题

**Comment by chianman719** [comment]
我想应该是源里的新版，我试试看有没有更新版的。谢谢回复！！发自我的华为手机-------- 原始邮件 --------发件人： NULL <notifications@github.com>日期： 2021年2月5日周五 下午3:26收件人： fgheng/vime <vime@noreply.github.com>抄送： chianman719 <yusihai719@163.com>, Author <author@noreply.github.com>主    题： Re: [fgheng/vime] nvim-treesitter-textobjects.vim 时发生 错误 (#16)

您好，请问您使用的是最新的neovim么？

我之前没有使用最新的neovim的时候也会出现问题

**Comment by fgheng** [comment]
因为neovim没有正式发布，所以源里的一般都是0.4版本的，你可以来这里下载最新版，直接解压就可以使用了。
https://github.com/neovim/neovim/releases
