### ISSUE TITLE
文件类型丢失

### ISSUE THREAD

**Issue by krisfans** [fgheng/vime#17]
打开文件偶尔会出现文件类型丢失的bug, 即lightline右下角下角出现no ft

**Comment by krisfans** [comment]
![Snipaste_2021-02-18_15-54-06](https://user-images.githubusercontent.com/57793534/108323423-9e38fa00-7201-11eb-84cb-170bc4118b14.png)

**Comment by fgheng** [comment]
您好，这个我还真没有注意过，为啥你的这个截图里的文字都是白的没有颜色呢？

**Comment by krisfans** [comment]
因为无法判断文件类型，所以没有启用语法高亮

**Comment by fgheng** [comment]
请问使用的是vim还是neovim呢？

**Comment by fgheng** [comment]
> 因为无法判断文件类型，所以没有启用语法高亮

这个问题我还真没有注意到过，要不你尝试下最新的neovim（https://github.com/neovim/neovim/releases）或者vim

**Comment by krisfans** [comment]
不是vim或者nvim的问题，因该是devicons 这个插件的问题，它应该放在最后加载
