### ISSUE TITLE
load file 出現 error

### ISSUE THREAD

**Issue by asd617140123** [fgheng/vime#18]
Hi 您好,
   目前使用到某些時候會出現下方的 訊息
然後需要點選 A 或 B 才能進入檔案,請問這是哪個功能?

![press the letter](https://user-images.githubusercontent.com/18673071/109613627-610f2900-7b6c-11eb-9aa3-3465838d8f74.png)

**Comment by fgheng** [comment]
您好，可以再详细一些么？
单看A或B的话，我怀疑是choose-win这个插件的问题，您可以去插件列表中注释掉该插件，然后看看还有没有问题
