### ISSUE TITLE
coc float win can not scroll normaly...

### ISSUE THREAD

**Issue by captainfffsama** [fgheng/vime#19]
您好,我fork了您的配置,然后修改了一些按键....
我的系统是 `ubuntu-18.04`
nvim version 是 
```
NVIM v0.5.0-dev+1157-g0ab88c2ea
Build type: Release
LuaJIT 2.1.0-beta3
```
使用时发现一个比较麻烦的问题....coc 在进行函数提示时出现的浮动窗口没法正常翻页...
使用鼠标滚轮,除非一直滚,否则浮动窗口就会跳转回顶端...
这导致了浮动窗口内容只能看最顶端或是最低端的内容...
这个问题,问过赵大,但是他表示也不清楚是哪里出了问题...

**Comment by fgheng** [comment]
您好，可以发个gif么？

**Comment by captainfffsama** [comment]
> 您好，可以发个gif么？

![problem](https://user-images.githubusercontent.com/40843698/111931522-5524e000-8af6-11eb-87ab-3503350c218f.gif)
ctrl+k 是像后翻页,按照赵大的coc里面设置的,设置方法如下:

**Comment by fgheng** [comment]
你好，我尝试了下，我这里没出现这个问题唉，可以正常的浏览，因为我目前在wayland下，所以录制的gif都是黑屏的，明天我换到x下面给你录个gif。
你可以尝试下赵大的c-j c-k的配置先去掉，看看还会出现这个问题么，我在keymap.vim中配置的c-j c-k c-h c-l是在窗口之间进行跳转。
如果还有问题的话，那你尝试下在插件列表中注释掉所有的插件，只留下coc这一个插件，看看是不是因为与其他插件冲突了。

**Comment by captainfffsama** [comment]
> 你好，我尝试了下，我这里没出现这个问题唉，可以正常的浏览，因为我目前在wayland下，所以录制的gif都是黑屏的，明天我换到x下面给你录个gif。
> 你可以尝试下赵大的c-j c-k的配置先去掉，看看还会出现这个问题么，我在keymap.vim中配置的c-j c-k c-h c-l是在窗口之间进行跳转。
> 如果还有问题的话，那你尝试下在插件列表中注释掉所有的插件，只留下coc这一个插件，看看是不是因为与其他插件冲突了。

您好,我仔细排查了一些...发现赵大提供的配置来设置coc浮窗翻页没啥问题...问题是:这一句[`au CursorHoldI * sil call CocActionAsync('showSignatureHelp')`](https://github.com/fgheng/vime/blob/bf82d5db65d872b7eca59ebdabf6a38115372592/config/plugins/coc.nvim.vim#L98)和`set updatetime=100`同时设置时,就会出现我这个问题= =|||...  目前我是将`au CursorHoldI * sil call CocActionAsync('showSignatureHelp')`注解掉.  然后使用赵大的配置定义一些快捷键,就可以正常浏览翻页了

**Comment by fgheng** [comment]
嗯嗯
