### ISSUE TITLE
關於 檔案預覽 圖標問題

### ISSUE THREAD

**Issue by asd617140123** [fgheng/vime#2]
Hi 下方是我的截圖
請問一下 圖標顯示都是亂碼?是因為什麼原因 
我已經在defx.vim 把錯誤的圖標先刪除 可是還是顯示有問題?
請問是還有須要改什麼嗎?

![註解 2020-07-30 163140](https://i.imgur.com/aAlH3fG.png)

**Comment by fgheng** [comment]
你好，很有可能是缺少字体，可以看一下这个https://github.com/ryanoasis/nerd-fonts。
对了，或许有可能缺少defx-icon插件或者是vim-devicons插件？因为我也好久不用defx了，所以我不清楚我说的对不对，非常抱歉。
这个vide我已经放弃了，我把vide重构成了vime了，如果可能的话，希望您可以换成vime，我记得vime的快捷键很多都与vide重复了，而且我把常用的快捷键都写到readme中了，便于查阅。

**Comment by krisfans** [comment]
怎样更改字体？
