### ISSUE TITLE
输入时经常会自动重复前面输入的文字

### ISSUE THREAD

**Issue by gyq716** [fgheng/vime#21]
在插入模式下写代码时，经常会出现自动重复前面输入的情况，请问这个是哪个插件或者配置引起的呢？还有就是一段时间光标会自动向下移动
![20210509223422](https://user-images.githubusercontent.com/53090231/117576069-ff90ab00-b116-11eb-942d-650a74efe1b5.jpg)

**Comment by fgheng** [comment]
您好，这个我还真没遇到过，请问你是用的neovim么？如果是neovim的话，你尝试下在config/layers.vim中将plugin_list.vim注释掉，然后打开simple.vim和git.vim，这两个文件中的插件相对来说少一些，但是也够用，看看会不会还会出现这个问题。

**Comment by gyq716** [comment]
> 还有一个解决方案就是直接在config/layers/plugin_list.vim中采用二分法进行排除，先注释掉一半的插件，然后看看还有没有这个问题，如果还存在的话就在注释掉剩下的插件中的一半，直到找到出问题的插件

感谢您的回复，问题已经找到了，是iterm设置的问题，不是neovim以及插件的问题
