### ISSUE TITLE
roxma/vim-tmux-clipboard 导致 neovim中 yyp 换行丢失，建议disable

### ISSUE THREAD

**Issue by jemyzhang** [fgheng/vime#23]
排查了所有的plugin，发现是roxma/vim-tmux-clipboard导致的。
相关issue：https://github.com/roxma/vim-tmux-clipboard/issues/4

**Comment by fgheng** [comment]
好的，感谢

**Comment by fgheng** [comment]
感谢反馈，已经disable了
