### ISSUE TITLE
Backspace 失效

### ISSUE THREAD

**Issue by swahpy** [fgheng/vime#28]
你好，安装之后 backspace 在insert mode下不会删除任何字符。请问这种情况需要更改哪个配置或者禁用哪个插件，谢谢。

**Comment by fgheng** [comment]
您好，这个真没有遇到过，您可以尝试使用二分法的方案来排除一下，在您的config/layers/plugin_list.vim(假设使用的是这个插件组合的话)文件中，注释掉一半，然后启动看看问题是否存在，如果不存在了，说明是注释掉的插件中的某一个，如果还存在那么说明是没有注释掉的插件中的一个

**Comment by fgheng** [comment]
如果您找到了可以告知一下哈，非常感谢

**Comment by swahpy** [comment]
抱歉，我没找到。因为不知道为什么问题消失了。
