### ISSUE TITLE
请求支持“显示python源代码类列表”

### ISSUE THREAD

**Issue by zfhxi** [fgheng/vime#29]
您好，我是vim新手，最近切换到neovim，主要写python代码。请问vime支持显示类列表、函数列表吗？怎么查看呢？

**Comment by fgheng** [comment]
您好，可以尝试下我最新的lua配置[vimelua](https://github.com/fgheng/vimelua)，按下\<F3\>之后会有一个函数列表窗口，支持显示python函数变量等，同时该配置也支持debug python代码。

现在已经可用了，但是目前我正在调整各个快捷键，以便使用起来更舒服，所以还没来得及写readme，后面我会将readme补上。

常用的几个快捷键如下所示：
\<f2\>在左侧打开资源管理器
\<f3\>在右侧打开函数列表
\<f5\>增加断点 debug模式需要安装debugpy
\<f9\>进入调试，执行到下一个断点
\<f12\>结束调试模式
\<space\>\<space\>打开telescope，可以进行各种各样的操作

**Comment by zfhxi** [comment]
> 您好，可以尝试下我最新的lua配置[vimelua](https://github.com/fgheng/vimelua)，按下<F3>之后会有一个函数列表窗口，支持显示python函数变量等，同时该配置也支持debug python代码。
> 
> 现在已经可用了，但是目前我正在调整各个快捷键，以便使用起来更舒服，所以还没来得及写readme，后面我会将readme补上。
> 
> 常用的几个快捷键如下所示： <f2>在左侧打开资源管理器 <f3>在右侧打开函数列表 <f5>增加断点 debug模式需要安装debugpy <f9>进入调试，执行到下一个断点 <f12>结束调试模式 <space><space>打开telescope，可以进行各种各样的操作

多谢您的回复，我后面试试

**Comment by fgheng** [comment]
vimelua的整体结构以及很多快捷键我都是尽量保持跟vime一致的
