### ISSUE TITLE
nerd tree 案 H 沒反應

### ISSUE THREAD

**Issue by asd617140123** [fgheng/vime#3]
您好 目前用您預設的主題
之前有用過vide 
在 目錄列 案h 可以回到上一層
用vime 案H 沒有反應
可以麻煩指教嗎?

**Comment by asd617140123** [comment]
另外我有寫一個script 可以讓 初次使用的人 把環境設定好
方便整進去嗎?

**Comment by fgheng** [comment]
> 另外我有寫一個script 可以讓 初次使用的人 把環境設定好
> 方便整進去嗎?

您好，可以的，但是我还不太了解怎么整合，您可以在这里简单介绍下过程么？非常感谢

**Comment by fgheng** [comment]
> 您好 目前用您預設的主題
> 之前有用過vide
> 在 目錄列 案h 可以回到上一層
> 用vime 案H 沒有反應
> 可以麻煩指教嗎?

因为我现在主要使用coc-explorer了，所以nerd tree好久没有配置过了，我看下是什么原因

**Comment by fgheng** [comment]
恩，nerdtree没有配置自定义的快捷键，使用的是默认的快捷键，这个我需要配置一下

**Comment by fgheng** [comment]
hello, 新的nerdtree的配置我已经更新了，现在可以使用hl cr backspace等按键了

**Comment by asd617140123** [comment]
hello,
好 我會測試看看
另外上次說的腳本,我會先fork,發pull request,
您再看要不要整進去
best regard,
Eric

NULL <notifications@github.com> 於 2020年9月29日 週二 下午12:29寫道：
