### ISSUE TITLE
vim新手请教let g:vim_root_path = expand('<sfile>:p:h') . '/'

### ISSUE THREAD

**Issue by hqabcxyxz** [fgheng/vime#5]
感谢大佬分享了自己的配置，这大概是我见过最清晰最易懂学习的vim配置了。

本人vim新手，学习大佬配置  不太懂为何init.vim中开始用的
`let g:vim_root_path = expand('<sfile>:p:h') . '/'` 这一句为何这样写，不是$MYVIMRC就可以得到vimrc的路径么？而且为何这个在我的nvim上echo出来是`/`而不是init.vim所在的目录呢？

再次感谢大佬的配置分享

**Comment by fgheng** [comment]
您好，我更改了，也改成$MYVIMRC了，使用`let g:vim_root_path = expand('<sfile>:p:h') . '/'`的话确实会存在一个问题（前提是这句放到autoload/common/common.vim中，在init.vim中没问题），就是只有在vim配置文件的根目录下启动vim才可以正确读取到文件路径，而在其他路径下启动vim就会出项问题，具体的原因我也不太清楚。
解决方案一个是将这句话放到init.vim中，这也是我最最开始的方案，另一个方案是使用$MYVIMRC了，这个就可以放到autoload/common/common.vim中了，我已经修改了，你可以尝试一下。
另外感谢你的建议，如果你有什么好的自定义的插件配置的话，也可以分享到这里

**Comment by hqabcxyxz** [comment]
感谢大佬回答，话说发现似乎是vim-plug  bug 
按照文件类型加载插件的时候  for 里面写py  不是不会加载的 要写python才会加载，具体的在plugin_list.vim文件中 ，关于indentLine插件 得改成python才加载= =||

**Comment by fgheng** [comment]
感谢提示，应该是我写错了，已经更改了。
